version: 2
jobs:
  build:
    working_directory: /go/src/github.com/mikhailadvani/terra-module
    docker:
      - image: golang:1.12
    steps:
      - checkout
      - run:
          name: install dependencies
          command: make install-deps
      - run:
          name: test
          command: make test
      - store_artifacts:
          path: cmd/testdata
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
